name: Geoportal Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Deploy via Rsync
        uses: Burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /home/u803460927/domains/carlosemendez.com/public_html/sig
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SERVER_PORT }}